model :
  - model_name: vit 
    num_classes : 102
    weights : "IMAGENET1K_V1" # DEFAULT
    dropout_rate: 0 # do not change yet

dataset : 
  - dataset_name : flowers102
    dataset_path : ../flowers_102

optimizer :
  - opt_name : adam
    lr : 0.0005
    warmup : 650
  
loss : 
  - loss_name : crossentropy

scheduler :
  - scheduler_name : steplr
    gamma : 0.15
    step_size : 10

training :
  - patience : 10
    epochs : 50
    mixUp : false