model :
  - model_name: vit 
    num_classes : 102
    weights : "IMAGENET1K_V1" # DEFAULT
    dropout_rate: 0 # do not change yet
    transformation: vit_default_transformation
    feature_extraction: true

dataset : 
  - dataset_name : flowers102
    dataset_path : ../flowers_102

optimizer :
  - opt_name : adam
    lr : 0.00004
    sam : true

loss : 
  - loss_name : multisimilarityloss

scheduler :
  - scheduler_name : steplr
    gamma : 0.5
    step_size : 10

training :
  - patience : 3
    epochs : 15
    mixUp : false
    continue_ckpt : '/home/UG/c200205/randaug_sam/output_model/model_best.pth.tar'